const CATEGORY_ENUM = {
  ID_CARD: 'ID_CARD',
  ID_CARD_FRONT: 'ID_CARD_FRONT',
  ID_CARD_BACK: 'ID_CARD_BACK',
  BANK_CARD: 'BANK_CARD',
  BUSINESS_CARD: 'BUSINESS_CARD',
};

module.exports = CATEGORY_ENUM;
