# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TencentCloudDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TencentCloudDemo
  pod 'AFNetworking','~> 3.1.0'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'

end
